name: canaluno
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  provider: ^6.1.2
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  brasil_fields: ^1.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
